image:
  repository: 194302643587.dkr.ecr.us-east-1.amazonaws.com/support-portal
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "8431693"

imagePullSecrets:
  - name: "ecr"

env:
  sealed:
    POSTGRES_PASSWORD: "AgB/SyDfSmp3so+L0H26Z0wCpLVSXWkoEa6i9x/Lx6tz4UFYTBW8ZVYD02/Osy+Cisa+GqJGB8umty71dwsmjgDWPwVieJnlCQnt6iKEx3gCmqBd4jXnzWsoSS88A+Jjgq8iEAp0VECRqb9IwtS5g5hWDjz/t6eRcvDSvpKk7HhFcOhBexnELgxqpVwALb9iLP/MdUe3h4HAr+JB76AqkwQD4zxHMfHh2H+hmukxPokKyiVjiPVcOBRbnxi0e58qf2CWIrd3p/KNN3OdEvQo/otHs948V/QTwYaN0DqwwcpgkXTcF8R+d17B2ku31lEeKBxEy1MKydP50eR65+GFj3jJXkdPcaK2Gl3MwDk3NccIW+F1d1wzID6RM8h41REqb1gC4luGaKRquBadiSLINbO49ReeMkdmPrcK5zDHrHkOzlA/2BCGE1G/dGzk0tv+z68ykr/rgmdR/l0VYLkKqF+2BydVuHt7rW82wmh+FL931qy2aI0iozdlLN/7EOSl3dddgn5EO9TpkLmh6BVF2gzdHL2xFGPIL/wnCX341UVzqCseCYL0xhk8cFWiu2OiUQO7BPsaZS0YE80Lo5Yi41dtaqpNUnVFSTxPKkoKYUSZ+5BTCnJeMhWQYkEpKyiZq3+QoFqLH8aMAyqqlYqJDMabNzzGu0p+PDFOCwHpGoDNLmBdlG8WC5+N85ES+j8YFwP3P4Em3f3VOg=="
  plain:
    POSTGRES_HOST: "postgres"
    POSTGRES_PORT: 5432
    POSTGRES_DATABASE: "support-portal"
    POSTGRES_USERNAME: "postgres"

hookJobs:
  - name: "migrations"
    annotations:
      "helm.sh/hook": pre-install,pre-upgrade
      "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
      "helm.sh/hook-weight": "2"
    image:
      repository: 194302643587.dkr.ecr.us-east-1.amazonaws.com/support-portal
      tag: "8431693-migrations"
    imagePullSecrets:
      - name: "ecr"
    backoffLimit: 0
    command: ["/bin/sh", "-c"]
    args:
      - >
        migrate -path=/migrations/ -database postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=disable up
    env:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        "helm.sh/hook": pre-install,pre-upgrade
        "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
        "helm.sh/hook-weight": "1"
      sealed:
        POSTGRES_PASSWORD: "AgB/SyDfSmp3so+L0H26Z0wCpLVSXWkoEa6i9x/Lx6tz4UFYTBW8ZVYD02/Osy+Cisa+GqJGB8umty71dwsmjgDWPwVieJnlCQnt6iKEx3gCmqBd4jXnzWsoSS88A+Jjgq8iEAp0VECRqb9IwtS5g5hWDjz/t6eRcvDSvpKk7HhFcOhBexnELgxqpVwALb9iLP/MdUe3h4HAr+JB76AqkwQD4zxHMfHh2H+hmukxPokKyiVjiPVcOBRbnxi0e58qf2CWIrd3p/KNN3OdEvQo/otHs948V/QTwYaN0DqwwcpgkXTcF8R+d17B2ku31lEeKBxEy1MKydP50eR65+GFj3jJXkdPcaK2Gl3MwDk3NccIW+F1d1wzID6RM8h41REqb1gC4luGaKRquBadiSLINbO49ReeMkdmPrcK5zDHrHkOzlA/2BCGE1G/dGzk0tv+z68ykr/rgmdR/l0VYLkKqF+2BydVuHt7rW82wmh+FL931qy2aI0iozdlLN/7EOSl3dddgn5EO9TpkLmh6BVF2gzdHL2xFGPIL/wnCX341UVzqCseCYL0xhk8cFWiu2OiUQO7BPsaZS0YE80Lo5Yi41dtaqpNUnVFSTxPKkoKYUSZ+5BTCnJeMhWQYkEpKyiZq3+QoFqLH8aMAyqqlYqJDMabNzzGu0p+PDFOCwHpGoDNLmBdlG8WC5+N85ES+j8YFwP3P4Em3f3VOg=="
      plain:
        POSTGRES_HOST: "postgres"
        POSTGRES_PORT: 5432
        POSTGRES_DATABASE: "support-portal"
        POSTGRES_USERNAME: "postgres"
  - name: "db-template"
    annotations:
      "helm.sh/hook": pre-install
      "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
      "helm.sh/hook-weight": "-1"
    image:
      repository: postgres
      tag: "latest"
    backoffLimit: 0
    command: ["/bin/bash", "-c"]
    args:
      - >
        psql postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=disable -c 'CREATE DATABASE "support-portal-preview" WITH TEMPLATE "support-portal";'
    env:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        "helm.sh/hook": pre-install
        "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
        "helm.sh/hook-weight": "-2"
      sealed:
        POSTGRES_PASSWORD: "AgB/SyDfSmp3so+L0H26Z0wCpLVSXWkoEa6i9x/Lx6tz4UFYTBW8ZVYD02/Osy+Cisa+GqJGB8umty71dwsmjgDWPwVieJnlCQnt6iKEx3gCmqBd4jXnzWsoSS88A+Jjgq8iEAp0VECRqb9IwtS5g5hWDjz/t6eRcvDSvpKk7HhFcOhBexnELgxqpVwALb9iLP/MdUe3h4HAr+JB76AqkwQD4zxHMfHh2H+hmukxPokKyiVjiPVcOBRbnxi0e58qf2CWIrd3p/KNN3OdEvQo/otHs948V/QTwYaN0DqwwcpgkXTcF8R+d17B2ku31lEeKBxEy1MKydP50eR65+GFj3jJXkdPcaK2Gl3MwDk3NccIW+F1d1wzID6RM8h41REqb1gC4luGaKRquBadiSLINbO49ReeMkdmPrcK5zDHrHkOzlA/2BCGE1G/dGzk0tv+z68ykr/rgmdR/l0VYLkKqF+2BydVuHt7rW82wmh+FL931qy2aI0iozdlLN/7EOSl3dddgn5EO9TpkLmh6BVF2gzdHL2xFGPIL/wnCX341UVzqCseCYL0xhk8cFWiu2OiUQO7BPsaZS0YE80Lo5Yi41dtaqpNUnVFSTxPKkoKYUSZ+5BTCnJeMhWQYkEpKyiZq3+QoFqLH8aMAyqqlYqJDMabNzzGu0p+PDFOCwHpGoDNLmBdlG8WC5+N85ES+j8YFwP3P4Em3f3VOg=="
      plain:
        POSTGRES_HOST: "postgres"
        POSTGRES_PORT: 5432
        POSTGRES_DATABASE: "support-portal"
        POSTGRES_USERNAME: "postgres"

livenessProbe:
  httpGet:
    path: /
    port: 8080

readinessProbe:
  httpGet:
    path: /
    port: 8080