{{- range .Values.hookJobs -}}
{{- if .serviceAccount.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "hook-{{ .name }}"
  labels:
    {{- include "base-chart.labels" $ | nindent 4 }}
  {{- with .serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}