{{- range .Values.hookJobs -}}
{{- if .env.sealed }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "hook-{{ .name }}"
  labels:
    {{- include "base-chart.labels" $ | nindent 4 }}
  {{- with .env.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  encryptedData:
  {{- range $key, $val := .env.sealed }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- end }}